apiVersion: v1
kind: Service
metadata:
  name: recipients-postgres
  namespace: prod
spec:
  clusterIP: None
  selector:
    app: recipients-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432