services:

  postgres:
    image: postgres:17-alpine
    container_name: recipients-postgres-17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: recipients_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d recipients_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recipients_network
    volumes:
      - recipients_postgres_volume:/var/lib/postgresql/data

  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"   # Grafana
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "3100:3100"   # Loki

volumes:
  recipients_postgres_volume:
    name: recipients-postgres-data

networks:
  recipients_network:
    name: recipients_network
