apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipients
  namespace: prod
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: recipients
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: recipients
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
      containers:
        - name: recipients
          image: jcondotta/recipients:1.0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: recipients-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: recipients-postgres-secret
                  key: POSTGRES_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipients-postgres-secret
                  key: POSTGRES_PASSWORD

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 400m
              memory: 800Mi
