name: accounts
services:

  localstack:
    container_name: "accounts-localstack-4.6.0"
    image: localstack/localstack:4.6.0
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      SERVICES: dynamodb
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      LS_LOG: ${LS_LOG:-debug}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking_network
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack:/etc/localstack/init/ready.d
      - accounts_localstack_volume:/var/lib/localstack

volumes:
  accounts_localstack_volume:
    name: accounts-localstack-data

networks:
  banking_network:
    external: true
    name: banking_network
