server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: accounts-system
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.write-dates-as-timestamps: false

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION}
    dynamodb:
      tables:
        banking-entities:
          table-name: ${AWS_DYNAMODB_BANK_ACCOUNTS_TABLE_NAME}

app:
  kafka:
    topics:
      bank-account-opened:
        topic-name: ${KAFKA_BANK_ACCOUNT_OPENED_TOPIC_NAME}
      bank-account-activated:
        topic-name: ${KAFKA_BANK_ACCOUNT_ACTIVATED_TOPIC_NAME}
      bank-account-blocked:
        topic-name: ${KAFKA_BANK_ACCOUNT_BLOCKED_TOPIC_NAME}
      bank-account-unblocked:
        topic-name: ${KAFKA_BANK_ACCOUNT_UNBLOCKED_TOPIC_NAME}
      bank-account-closed:
        topic-name: ${KAFKA_BANK_ACCOUNT_CLOSED_TOPIC_NAME}
      joint-account-holder-added:
        topic-name: ${KAFKA_JOINT_ACCOUNT_HOLDER_ADDED_TOPIC_NAME}

api:
  v1:
    bank-accounts:
      root-path: '/api/v1/bank-accounts'
      bank-account-id-path: '/api/v1/bank-accounts/{bank-account-id}'
      account-holders-path: '/api/v1/bank-accounts/{bank-account-id}/account-holders'

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        bankAccounts.open: true
        bankAccounts.activate: true
        bankAccounts.block: true
#        cache.get: true
#        cache.put_if_absent: true
#        cache.put: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        bankAccounts.open: 0.5, 0.95, 0.99
        bankAccounts.activate: 0.5, 0.95, 0.99
        bankAccounts.block: 0.5, 0.95, 0.99
#        cache.get: 0.5, 0.95, 0.99
#        cache.put_if_absent: 0.5, 0.95, 0.99
#        cache.put: 0.5, 0.95, 0.99