apiVersion: v1
kind: ConfigMap
metadata:
  name: recipients-config
  namespace: prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://recipients-postgres:5432/recipients_db"
