server:
  port: ${SERVER_PORT:8096}

app:
  environment: ${APPLICATION_ENV}

spring:
  application:
    name: account-recipients

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION}
    dynamodb:
      tables:
        account-recipients:
          table-name: ${AWS_DYNAMODB_ACCOUNT_RECIPIENTS_TABLE_NAME}

api:
  v1:
    recipients:
      root-path: '/api/v1/bank-accounts/{bank-account-id}/recipients'
      recipient-id-path: '/api/v1/bank-accounts/{bank-account-id}/recipients/{recipient-id}'

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        http.server.requests: true
        bankaccount.*: true

      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        bankaccount.*: 0.5, 0.95, 0.99