app:
  environment: ${APPLICATION_ENV:local}

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION:us-east-1}
    credentials:
      access-key-id: ${AWS_ACCESS_KEY_ID:test}
      secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    dynamodb:
      endpoint: ${AWS_DYNAMODB_ENDPOINT:http://127.0.0.1:4566}
      tables:
        account-recipients:
          table-name: ${AWS_DYNAMODB_ACCOUNT_RECIPIENTS_TABLE_NAME:account-recipients}