server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipients_db?connectTimeout=3&socketTimeout=5
    username: admin
    password: password

  jpa:
    show-sql: false

management:
  data-prepper:
    logging:
      url: http://localhost:2021/log/ingest/

  otlp:
    metrics:
      export:
        enabled: false
